##################################
# Checkout the documentation at: #
#  alexandre2006.github.io/docs  #
##################################

##################################
#            Settings            #
##################################

INCREASING_STRENGTH: true # Increases the strength of the effect every time the player gets hit
IMMUNITY_ITEM: true # Whether there should be an item which grants immunity

##################################
#             Crafts             #
#   (check docs for item list)   #
##################################

ITEM: COOKIE # The item that the immunity item will be
RECIPE: # The recipe for the immunity item from slot 1-9 of the crafting table
  1: COOKIE
  2: COOKIE
  3: COOKIE
  4: COOKIE
  5: MILK_BUCKET
  6: COOKIE
  7: COOKIE
  8: COOKIE
  9: COOKIE
NAME: Immunity Cookie # The name of the immunity item
LORE: Grants immunity to Mob Effects # Text under name
ENCHANTED: true # Whether the enchanted glowing effect should be applied

###################################
#          Potion Effects         #
#  (check docs for effects list)  #
###################################

Example:
  EFFECT: REGENERATION # The name of the effect
  DURATION: 100 # The duration of the effect in ticks
  BASESTRENGTH: 1 # The base strength of the effect
  MAXSTRENGTH: 255 # The maximum strength of the effect

BEE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

BLAZE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

CAVE_SPIDER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

CREEPER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

DOLPHIN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

DROWNED:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ELDER_GUARDIAN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ENDER_DRAGON:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ENDERMAN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ENDERMITE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

EVOKER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

FOX:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

GHAST:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

GUARDIAN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

HOGLIN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

HUSK:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ILLUSIONER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

IRON_GOLEM:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

LLAMA:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

MAGMA_CUBE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PANDA:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PHANTOM:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PIGLIN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PIGLIN_BRUTE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PILLAGER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

POLAR_BEAR:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

PUFFERFISH:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

RABBIT:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

RAVAGER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

SHULKER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

SILVERFISH:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

SKELETON:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

SLIME:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

SPIDER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

STRAY:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

VEX:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

VINDICATOR:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

WITCH:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

WITHER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

WITHER_SKELETON:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

WOLF:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ZOGLIN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ZOMBIE:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ZOMBIFIED_PIGLIN:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH:

ZOMBIE_VILLAGER:
  EFFECT:
  DURATION:
  BASESTRENGTH:
  MAXSTRENGTH: